import { UserRole } from "../types";


// shared/src/constants/permissions.ts
export const USER_PERMISSIONS = {
  // Permissions système
  MANAGE_ROLES: 'manage_roles',
  MANAGE_SYSTEM_SETTINGS: 'manage_system_settings',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  MANAGE_SMS_PROVIDERS: 'manage_sms_providers',
  MANAGE_EMAIL_PROVIDERS: 'manage_email_providers',
  EXPORT_ALL_DATA: 'export_all_data',
  
  // Permissions utilisateurs
  MANAGE_USERS: 'manage_users',
  VIEW_ALL_USERS: 'view_all_users',
  CREATE_ADMIN_USERS: 'create_admin_users',
  DELETE_ANY_USER: 'delete_any_user',
  RESET_ANY_PASSWORD: 'reset_any_password',
  VIEW_TEAM_USERS: 'view_team_users',
  CREATE_PARTICIPANTS: 'create_participants',
  EDIT_TEAM_PROFILES: 'edit_team_profiles',
  UPDATE_PROFILE: 'update_profile',
  
  // Permissions événements
  CREATE_EVENTS: 'create_events',
  EDIT_EVENTS: 'edit_events',
  DELETE_EVENTS: 'delete_events',
  DELETE_OWN_EVENTS: 'delete_own_events',
  VIEW_ALL_EVENTS: 'view_all_events',
  VIEW_OWN_EVENTS: 'view_own_events',
  VIEW_PUBLIC_EVENTS: 'view_public_events',
  GENERATE_QR_CODES: 'generate_qr_codes',
  
  // Permissions présences
  MARK_ATTENDANCE: 'mark_attendance',
  VALIDATE_ATTENDANCES: 'validate_attendances',
  VALIDATE_TEAM_ATTENDANCES: 'validate_team_attendances',
  VIEW_ALL_ATTENDANCES: 'view_all_attendances',
  VIEW_EVENT_ATTENDANCES: 'view_event_attendances',
  VIEW_TEAM_ATTENDANCES: 'view_team_attendances',
  VIEW_OWN_ATTENDANCE: 'view_own_attendance',
  DELETE_ATTENDANCES: 'delete_attendances',
  
  // Permissions rapports
  GENERATE_ALL_REPORTS: 'generate_all_reports',
  GENERATE_EVENT_REPORTS: 'generate_event_reports',
  GENERATE_TEAM_REPORTS: 'generate_team_reports',
  EXPORT_EVENT_DATA: 'export_event_data',
  
  // Permissions notifications
  SEND_SYSTEM_NOTIFICATIONS: 'send_system_notifications',
  SEND_EVENT_NOTIFICATIONS: 'send_event_notifications',
  VIEW_NOTIFICATIONS: 'view_notifications',
  MARK_NOTIFICATIONS_READ: 'mark_notifications_read',
  
  // Permissions templates
  MANAGE_TEMPLATES: 'manage_templates'
} as const;

export const PERMISSION_CATEGORIES = {
  SYSTEM: 'Système',
  USERS: 'Utilisateurs', 
  EVENTS: 'Événements',
  ATTENDANCE: 'Présences',
  REPORTS: 'Rapports',
  NOTIFICATIONS: 'Notifications',
  TEMPLATES: 'Templates'
} as const;

export const PERMISSION_LABELS = {
  [USER_PERMISSIONS.MANAGE_ROLES]: 'Gérer les rôles et permissions',
  [USER_PERMISSIONS.MANAGE_SYSTEM_SETTINGS]: 'Configurer les paramètres système',
  [USER_PERMISSIONS.VIEW_AUDIT_LOGS]: 'Consulter les logs d\'audit',
  [USER_PERMISSIONS.MANAGE_SMS_PROVIDERS]: 'Gérer les fournisseurs SMS',
  [USER_PERMISSIONS.MANAGE_EMAIL_PROVIDERS]: 'Gérer les fournisseurs d\'email',
  [USER_PERMISSIONS.EXPORT_ALL_DATA]: 'Exporter toutes les données',
  
  [USER_PERMISSIONS.MANAGE_USERS]: 'Gérer tous les utilisateurs',
  [USER_PERMISSIONS.VIEW_ALL_USERS]: 'Voir tous les utilisateurs',
  [USER_PERMISSIONS.CREATE_ADMIN_USERS]: 'Créer des utilisateurs admin',
  [USER_PERMISSIONS.DELETE_ANY_USER]: 'Supprimer n\'importe quel utilisateur',
  [USER_PERMISSIONS.RESET_ANY_PASSWORD]: 'Réinitialiser n\'importe quel mot de passe',
  [USER_PERMISSIONS.VIEW_TEAM_USERS]: 'Voir les utilisateurs de son équipe',
  [USER_PERMISSIONS.CREATE_PARTICIPANTS]: 'Créer des utilisateurs participants',
  [USER_PERMISSIONS.EDIT_TEAM_PROFILES]: 'Modifier les profils de son équipe',
  [USER_PERMISSIONS.UPDATE_PROFILE]: 'Mettre à jour son profil',
  
  [USER_PERMISSIONS.CREATE_EVENTS]: 'Créer des événements',
  [USER_PERMISSIONS.EDIT_EVENTS]: 'Modifier des événements',
  [USER_PERMISSIONS.DELETE_EVENTS]: 'Supprimer n\'importe quel événement',
  [USER_PERMISSIONS.DELETE_OWN_EVENTS]: 'Supprimer ses propres événements',
  [USER_PERMISSIONS.VIEW_ALL_EVENTS]: 'Voir tous les événements',
  [USER_PERMISSIONS.VIEW_OWN_EVENTS]: 'Voir ses propres événements',
  [USER_PERMISSIONS.VIEW_PUBLIC_EVENTS]: 'Voir les événements publics',
  [USER_PERMISSIONS.GENERATE_QR_CODES]: 'Générer des codes QR',
  
  [USER_PERMISSIONS.MARK_ATTENDANCE]: 'Marquer sa présence',
  [USER_PERMISSIONS.VALIDATE_ATTENDANCES]: 'Valider les présences',
  [USER_PERMISSIONS.VALIDATE_TEAM_ATTENDANCES]: 'Valider les présences de son équipe',
  [USER_PERMISSIONS.VIEW_ALL_ATTENDANCES]: 'Voir toutes les présences',
  [USER_PERMISSIONS.VIEW_EVENT_ATTENDANCES]: 'Voir les présences d\'un événement',
  [USER_PERMISSIONS.VIEW_TEAM_ATTENDANCES]: 'Voir les présences de son équipe',
  [USER_PERMISSIONS.VIEW_OWN_ATTENDANCE]: 'Voir ses propres présences',
  [USER_PERMISSIONS.DELETE_ATTENDANCES]: 'Supprimer des présences',
  
  [USER_PERMISSIONS.GENERATE_ALL_REPORTS]: 'Générer tous types de rapports',
  [USER_PERMISSIONS.GENERATE_EVENT_REPORTS]: 'Générer des rapports pour ses événements',
  [USER_PERMISSIONS.GENERATE_TEAM_REPORTS]: 'Générer des rapports pour son équipe',
  [USER_PERMISSIONS.EXPORT_EVENT_DATA]: 'Exporter les données de ses événements',
  
  [USER_PERMISSIONS.SEND_SYSTEM_NOTIFICATIONS]: 'Envoyer des notifications système',
  [USER_PERMISSIONS.SEND_EVENT_NOTIFICATIONS]: 'Envoyer des notifications pour ses événements',
  [USER_PERMISSIONS.VIEW_NOTIFICATIONS]: 'Voir ses notifications',
  [USER_PERMISSIONS.MARK_NOTIFICATIONS_READ]: 'Marquer ses notifications comme lues',
  
  [USER_PERMISSIONS.MANAGE_TEMPLATES]: 'Gérer les templates (email, SMS)'
} as const;

// Mapping des permissions par rôle
export const ROLE_PERMISSIONS = {
  [UserRole.SUPER_ADMIN]: [
    USER_PERMISSIONS.MANAGE_ROLES,
    USER_PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
    USER_PERMISSIONS.DELETE_ANY_USER,
    USER_PERMISSIONS.RESET_ANY_PASSWORD,
    USER_PERMISSIONS.VIEW_AUDIT_LOGS,
    USER_PERMISSIONS.MANAGE_SMS_PROVIDERS,
    USER_PERMISSIONS.MANAGE_EMAIL_PROVIDERS,
    USER_PERMISSIONS.EXPORT_ALL_DATA,
    // Hérite de ADMIN
    USER_PERMISSIONS.MANAGE_USERS,
    USER_PERMISSIONS.VIEW_ALL_USERS,
    USER_PERMISSIONS.VIEW_ALL_EVENTS,
    USER_PERMISSIONS.VIEW_ALL_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_ALL_REPORTS,
    USER_PERMISSIONS.CREATE_ADMIN_USERS,
    USER_PERMISSIONS.DELETE_EVENTS,
    USER_PERMISSIONS.DELETE_ATTENDANCES,
    USER_PERMISSIONS.MANAGE_TEMPLATES,
    USER_PERMISSIONS.SEND_SYSTEM_NOTIFICATIONS,
    // Hérite de ORGANIZER
    USER_PERMISSIONS.CREATE_EVENTS,
    USER_PERMISSIONS.EDIT_EVENTS,
    USER_PERMISSIONS.DELETE_OWN_EVENTS,
    USER_PERMISSIONS.VIEW_EVENT_ATTENDANCES,
    USER_PERMISSIONS.VALIDATE_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_QR_CODES,
    USER_PERMISSIONS.SEND_EVENT_NOTIFICATIONS,
    USER_PERMISSIONS.GENERATE_EVENT_REPORTS,
    USER_PERMISSIONS.EXPORT_EVENT_DATA,
    // Hérite de MANAGER
    USER_PERMISSIONS.VIEW_TEAM_USERS,
    USER_PERMISSIONS.VIEW_TEAM_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_TEAM_REPORTS,
    USER_PERMISSIONS.VALIDATE_TEAM_ATTENDANCES,
    USER_PERMISSIONS.CREATE_PARTICIPANTS,
    USER_PERMISSIONS.EDIT_TEAM_PROFILES,
    // Hérite de PARTICIPANT
    USER_PERMISSIONS.MARK_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_EVENTS,
    USER_PERMISSIONS.UPDATE_PROFILE,
    USER_PERMISSIONS.VIEW_NOTIFICATIONS,
    USER_PERMISSIONS.MARK_NOTIFICATIONS_READ,
    // Hérite de GUEST
    USER_PERMISSIONS.VIEW_PUBLIC_EVENTS
  ],
  
  [UserRole.ADMIN]: [
    USER_PERMISSIONS.MANAGE_USERS,
    USER_PERMISSIONS.VIEW_ALL_USERS,
    USER_PERMISSIONS.VIEW_ALL_EVENTS,
    USER_PERMISSIONS.VIEW_ALL_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_ALL_REPORTS,
    USER_PERMISSIONS.CREATE_ADMIN_USERS,
    USER_PERMISSIONS.DELETE_EVENTS,
    USER_PERMISSIONS.DELETE_ATTENDANCES,
    USER_PERMISSIONS.MANAGE_TEMPLATES,
    USER_PERMISSIONS.SEND_SYSTEM_NOTIFICATIONS,
    // Hérite de ORGANIZER
    USER_PERMISSIONS.CREATE_EVENTS,
    USER_PERMISSIONS.EDIT_EVENTS,
    USER_PERMISSIONS.DELETE_OWN_EVENTS,
    USER_PERMISSIONS.VIEW_EVENT_ATTENDANCES,
    USER_PERMISSIONS.VALIDATE_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_QR_CODES,
    USER_PERMISSIONS.SEND_EVENT_NOTIFICATIONS,
    USER_PERMISSIONS.GENERATE_EVENT_REPORTS,
    USER_PERMISSIONS.EXPORT_EVENT_DATA,
    // Hérite de MANAGER
    USER_PERMISSIONS.VIEW_TEAM_USERS,
    USER_PERMISSIONS.VIEW_TEAM_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_TEAM_REPORTS,
    USER_PERMISSIONS.VALIDATE_TEAM_ATTENDANCES,
    USER_PERMISSIONS.CREATE_PARTICIPANTS,
    USER_PERMISSIONS.EDIT_TEAM_PROFILES,
    // Hérite de PARTICIPANT
    USER_PERMISSIONS.MARK_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_EVENTS,
    USER_PERMISSIONS.UPDATE_PROFILE,
    USER_PERMISSIONS.VIEW_NOTIFICATIONS,
    USER_PERMISSIONS.MARK_NOTIFICATIONS_READ,
    // Hérite de GUEST
    USER_PERMISSIONS.VIEW_PUBLIC_EVENTS
  ],
  
  [UserRole.ORGANIZER]: [
    USER_PERMISSIONS.CREATE_EVENTS,
    USER_PERMISSIONS.EDIT_EVENTS,
    USER_PERMISSIONS.DELETE_OWN_EVENTS,
    USER_PERMISSIONS.VIEW_EVENT_ATTENDANCES,
    USER_PERMISSIONS.VALIDATE_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_QR_CODES,
    USER_PERMISSIONS.SEND_EVENT_NOTIFICATIONS,
    USER_PERMISSIONS.GENERATE_EVENT_REPORTS,
    USER_PERMISSIONS.EXPORT_EVENT_DATA,
    // Hérite de MANAGER
    USER_PERMISSIONS.VIEW_TEAM_USERS,
    USER_PERMISSIONS.VIEW_TEAM_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_TEAM_REPORTS,
    USER_PERMISSIONS.VALIDATE_TEAM_ATTENDANCES,
    USER_PERMISSIONS.CREATE_PARTICIPANTS,
    USER_PERMISSIONS.EDIT_TEAM_PROFILES,
    // Hérite de PARTICIPANT
    USER_PERMISSIONS.MARK_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_EVENTS,
    USER_PERMISSIONS.UPDATE_PROFILE,
    USER_PERMISSIONS.VIEW_NOTIFICATIONS,
    USER_PERMISSIONS.MARK_NOTIFICATIONS_READ,
    // Hérite de GUEST
    USER_PERMISSIONS.VIEW_PUBLIC_EVENTS
  ],
  
  [UserRole.MANAGER]: [
    USER_PERMISSIONS.VIEW_TEAM_USERS,
    USER_PERMISSIONS.VIEW_TEAM_ATTENDANCES,
    USER_PERMISSIONS.GENERATE_TEAM_REPORTS,
    USER_PERMISSIONS.VALIDATE_TEAM_ATTENDANCES,
    USER_PERMISSIONS.CREATE_PARTICIPANTS,
    USER_PERMISSIONS.EDIT_TEAM_PROFILES,
    // Hérite de PARTICIPANT
    USER_PERMISSIONS.MARK_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_EVENTS,
    USER_PERMISSIONS.UPDATE_PROFILE,
    USER_PERMISSIONS.VIEW_NOTIFICATIONS,
    USER_PERMISSIONS.MARK_NOTIFICATIONS_READ,
    // Hérite de GUEST
    USER_PERMISSIONS.VIEW_PUBLIC_EVENTS
  ],
  
  [UserRole.PARTICIPANT]: [
    USER_PERMISSIONS.MARK_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_ATTENDANCE,
    USER_PERMISSIONS.VIEW_OWN_EVENTS,
    USER_PERMISSIONS.UPDATE_PROFILE,
    USER_PERMISSIONS.VIEW_NOTIFICATIONS,
    USER_PERMISSIONS.MARK_NOTIFICATIONS_READ,
    // Hérite de GUEST
    USER_PERMISSIONS.VIEW_PUBLIC_EVENTS
  ],
  
  [UserRole.GUEST]: [
    USER_PERMISSIONS.VIEW_PUBLIC_EVENTS
  ]
} as const;

// Groupement des permissions par catégorie
export const PERMISSIONS_BY_CATEGORY = {
  [PERMISSION_CATEGORIES.SYSTEM]: [
    USER_PERMISSIONS.MANAGE_ROLES,
    USER_PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
    USER_PERMISSIONS.VIEW_AUDIT_LOGS,
    USER_PERMISSIONS.MANAGE_SMS_PROVIDERS,
    USER_PERMISSIONS.MANAGE_EMAIL_PROVIDERS,
    USER_PERMISSIONS.EXPORT_ALL_DATA
  ],
  [PERMISSION_CATEGORIES.USERS]: [
    USER_PERMISSIONS.MANAGE_USERS,
    USER_PERMISSIONS.VIEW_ALL_USERS,
    USER_PERMISSIONS.CREATE_ADMIN_USERS,
    USER_PERMISSIONS.DELETE_ANY_USER,
    USER_PERMISSIONS.RESET_ANY_PASSWORD,
    USER_PERMISSIONS.VIEW_TEAM_USERS,
    USER_PERMISSIONS.CREATE_PARTICIPANTS,
    USER_PERMISSIONS.EDIT_TEAM_PROFILES,
    USER_PERMISSIONS.UPDATE_PROFILE
  ],
  [PERMISSION_CATEGORIES.EVENTS]: [
    USER_PERMISSIONS.CREATE_EVENTS,
    USER_PERMISSIONS.EDIT_EVENTS,
    USER_PERMISSIONS.DELETE_EVENTS,
    USER_PERMISSIONS.DELETE_OWN_EVENTS,
    USER_PERMISSIONS.VIEW_ALL_EVENTS,
    USER_PERMISSIONS.VIEW_OWN_EVENTS,
    USER_PERMISSIONS.VIEW_PUBLIC_EVENTS,
    USER_PERMISSIONS.GENERATE_QR_CODES
  ],
  [PERMISSION_CATEGORIES.ATTENDANCE]: [
    USER_PERMISSIONS.MARK_ATTENDANCE,
    USER_PERMISSIONS.VALIDATE_ATTENDANCES,
    USER_PERMISSIONS.VALIDATE_TEAM_ATTENDANCES,
    USER_PERMISSIONS.VIEW_ALL_ATTENDANCES,
    USER_PERMISSIONS.VIEW_EVENT_ATTENDANCES,
    USER_PERMISSIONS.VIEW_TEAM_ATTENDANCES,
    USER_PERMISSIONS.VIEW_OWN_ATTENDANCE,
    USER_PERMISSIONS.DELETE_ATTENDANCES
  ],
  [PERMISSION_CATEGORIES.REPORTS]: [
    USER_PERMISSIONS.GENERATE_ALL_REPORTS,
    USER_PERMISSIONS.GENERATE_EVENT_REPORTS,
    USER_PERMISSIONS.GENERATE_TEAM_REPORTS,
    USER_PERMISSIONS.EXPORT_EVENT_DATA
  ],
  [PERMISSION_CATEGORIES.NOTIFICATIONS]: [
    USER_PERMISSIONS.SEND_SYSTEM_NOTIFICATIONS,
    USER_PERMISSIONS.SEND_EVENT_NOTIFICATIONS,
    USER_PERMISSIONS.VIEW_NOTIFICATIONS,
    USER_PERMISSIONS.MARK_NOTIFICATIONS_READ
  ],
  [PERMISSION_CATEGORIES.TEMPLATES]: [
    USER_PERMISSIONS.MANAGE_TEMPLATES
  ]
} as const;