# Configuration Prometheus pour AttendanceX
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Règles d'alerte
rule_files:
  - "alert_rules.yml"

# Configuration des alertes
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Cibles de scraping
scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (métriques système)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Backend AttendanceX
  - job_name: 'attendancex-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # Frontend AttendanceX (si métriques exposées)
  - job_name: 'attendancex-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  # Métriques personnalisées AttendanceX
  - job_name: 'attendancex-custom'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/api/custom-metrics'
    scrape_interval: 30s
    params:
      format: ['prometheus']